export function normalizeCityKey(value) {
  return String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

export function isBogotaSiberiaCityName(value) {
  return ['bogota', 'bogota d.c.', 'bogota dc', 'siberia'].includes(normalizeCityKey(value));
}

export function operationalCityNamesEquivalent(left, right) {
  const leftKey = normalizeCityKey(left);
  const rightKey = normalizeCityKey(right);
  if (!leftKey || !rightKey) return false;
  if (leftKey === rightKey) return true;
  return isBogotaSiberiaCityName(left) && isBogotaSiberiaCityName(right);
}

export function operationalCityScopeAllowsName(scope, cityName, { selected = true } = {}) {
  if (!scope?.restricted && (!selected || scope?.selectionExplicit !== true)) return true;
  if (!normalizeCityKey(cityName)) return false;
  const cities = selected ? scope?.selectedCities : scope?.allowedCities;
  return (cities || []).some((city) => operationalCityNamesEquivalent(city?.name, cityName));
}

export function filterOperationalClientsByCityScope(clients, scope, { selected = false } = {}) {
  if (!Array.isArray(clients) || (!scope?.restricted && (!selected || scope?.selectionExplicit !== true))) return clients;
  return clients.flatMap((client) => {
    const operationPoints = (client.operationPoints || []).filter((point) => (
      operationalCityScopeAllowsName(scope, point.cityName || client.cityName, { selected })
    ));
    if (!operationalCityScopeAllowsName(scope, client.cityName, { selected }) && !operationPoints.length) return [];
    return [{ ...client, operationPoints }];
  });
}

export function isAutoGeneratedCity(city) {
  return typeof city?.id === 'string' && city.id.startsWith('city_');
}

function countDiacritics(value) {
  return [...String(value || '')]
    .filter((character) => character.normalize('NFD') !== character)
    .length;
}

function preferCanonicalCity(current, candidate) {
  const currentDiacritics = countDiacritics(current?.name);
  const candidateDiacritics = countDiacritics(candidate?.name);
  if (candidateDiacritics !== currentDiacritics) {
    return candidateDiacritics > currentDiacritics ? candidate : current;
  }
  return current;
}

export function dedupeCitiesByNormalizedName(cities = []) {
  const byNormalizedName = new Map();

  for (const city of cities) {
    if (isAutoGeneratedCity(city)) continue;
    const key = normalizeCityKey(city?.name);
    if (!key) continue;
    const current = byNormalizedName.get(key);
    byNormalizedName.set(key, current ? preferCanonicalCity(current, city) : city);
  }

  return [...byNormalizedName.values()]
    .sort((a, b) => String(a.name || '').localeCompare(String(b.name || ''), 'es'));
}

export async function loadUnifiedCityOptions(prisma) {
  const cities = await prisma.city.findMany({
    where: { NOT: { id: { startsWith: 'city_' } } },
    orderBy: { name: 'asc' }
  });
  return dedupeCitiesByNormalizedName(cities);
}

export async function resolveEquivalentCityIds(prisma, cityId) {
  if (!cityId) return [];

  const selectedCity = await prisma.city.findFirst({
    where: { id: cityId, NOT: { id: { startsWith: 'city_' } } },
    select: { id: true, name: true }
  });
  if (!selectedCity) return [cityId];

  const selectedKey = normalizeCityKey(selectedCity.name);
  const cities = await prisma.city.findMany({
    where: { NOT: { id: { startsWith: 'city_' } } },
    select: { id: true, name: true }
  });

  const equivalentIds = cities
    .filter((city) => normalizeCityKey(city.name) === selectedKey)
    .map((city) => city.id);

  return equivalentIds.length ? equivalentIds : [selectedCity.id];
}
