import {
  normalizeUserAccessCities,
  normalizeUserAccessScope
} from './appUsers.js';

function normalizeString(value) {
  if (typeof value !== 'string') return null;
  const text = value.trim();
  return text || null;
}

function sourceValue(source = {}, key) {
  return source?.[key] ?? source?.session?.[key] ?? null;
}

function normalizeStringList(value) {
  const values = Array.isArray(value) ? value : value === null || value === undefined ? [] : [value];
  return [...new Set(values.map((item) => normalizeString(item)).filter(Boolean))];
}

export function normalizeCityKey(value) {
  return String(value || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

export function isBogotaSiberiaCityName(value) {
  return ['bogota', 'bogota d.c.', 'bogota dc', 'siberia'].includes(normalizeCityKey(value));
}

export function canonicalOperationalBranchName(value) {
  const normalized = normalizeString(value);
  if (!normalized) return null;
  return isBogotaSiberiaCityName(normalized) ? 'Bogotá' : normalized;
}

export function operationalCityNamesEquivalent(left, right) {
  const leftKey = normalizeCityKey(left);
  const rightKey = normalizeCityKey(right);
  if (!leftKey || !rightKey) return false;
  if (leftKey === rightKey) return true;
  return isBogotaSiberiaCityName(left) && isBogotaSiberiaCityName(right);
}

export function operationalCityScopeAllowsName(scope, cityName, { selected = true } = {}) {
  if (!scope?.restricted && (!selected || scope?.selectionExplicit !== true)) return true;
  if (!normalizeCityKey(cityName)) return false;
  const cities = selected ? scope?.selectedCities : scope?.allowedCities;
  return (cities || []).some((city) => operationalCityNamesEquivalent(city?.name, cityName));
}

export function operationalCityIdsAllowed(scope, cityIds) {
  if (!scope?.restricted) return true;
  const allowedIds = new Set(scope.allowedCityIds || []);
  return normalizeStringList(cityIds).every((cityId) => allowedIds.has(cityId));
}

export function workerMatchesOperationalCityScope(worker, scope, { selected = false } = {}) {
  if (!scope?.restricted && (!selected || scope?.selectionExplicit !== true)) return true;
  const assignedCityNames = (worker?.cities || [])
    .map((entry) => entry?.city?.name || entry?.name)
    .filter(Boolean);
  if (assignedCityNames.length) {
    return assignedCityNames.some((name) => operationalCityScopeAllowsName(scope, name, { selected }));
  }
  return operationalCityScopeAllowsName(scope, worker?.residenceCity, { selected });
}

export function clientMatchesOperationalCityScope(client, scope, { selected = false } = {}) {
  if (!scope?.restricted && (!selected || scope?.selectionExplicit !== true)) return true;
  const branchCityIds = normalizeStringList(client?.branchCityIds);
  if (branchCityIds.length) {
    const visibleIds = new Set(selected ? scope?.selectedCityIds : scope?.allowedCityIds);
    return branchCityIds.some((cityId) => visibleIds.has(cityId));
  }

  if (operationalCityScopeAllowsName(scope, client?.cityName, { selected })) return true;
  return (client?.operationPoints || []).some((point) => (
    operationalCityScopeAllowsName(scope, point?.cityName || client?.cityName, { selected })
  ));
}

export function filterOperationalClientsByCityScope(clients, scope, { selected = false } = {}) {
  if (!Array.isArray(clients) || (!scope?.restricted && (!selected || scope?.selectionExplicit !== true))) return clients;
  return clients.flatMap((client) => {
    const operationPoints = (client.operationPoints || []).filter((point) => (
      operationalCityScopeAllowsName(scope, point.cityName || client.cityName, { selected })
    ));
    if (!clientMatchesOperationalCityScope(client, scope, { selected }) && !operationPoints.length) return [];
    return [{ ...client, operationPoints }];
  });
}

export function isAutoGeneratedCity(city) {
  return typeof city?.id === 'string' && city.id.startsWith('city_');
}

function countDiacritics(value) {
  return [...String(value || '')]
    .filter((character) => character.normalize('NFD') !== character)
    .length;
}

function preferCanonicalCity(current, candidate) {
  const currentDiacritics = countDiacritics(current?.name);
  const candidateDiacritics = countDiacritics(candidate?.name);
  if (candidateDiacritics !== currentDiacritics) {
    return candidateDiacritics > currentDiacritics ? candidate : current;
  }
  return current;
}

function preferOperationalBranchCity(current, candidate) {
  if (isBogotaSiberiaCityName(current?.name) && isBogotaSiberiaCityName(candidate?.name)) {
    const currentIsSiberia = normalizeCityKey(current?.name) === 'siberia';
    const candidateIsSiberia = normalizeCityKey(candidate?.name) === 'siberia';
    if (currentIsSiberia !== candidateIsSiberia) return currentIsSiberia ? candidate : current;
  }
  return preferCanonicalCity(current, candidate);
}

function cityEquivalentIds(city) {
  return normalizeStringList(city?.equivalentCityIds?.length ? city.equivalentCityIds : city?.id);
}

export function dedupeCitiesByNormalizedName(cities = []) {
  const byNormalizedName = new Map();

  for (const city of cities) {
    if (isAutoGeneratedCity(city)) continue;
    const key = normalizeCityKey(city?.name);
    if (!key) continue;
    const current = byNormalizedName.get(key);
    byNormalizedName.set(key, current ? preferCanonicalCity(current, city) : city);
  }

  return [...byNormalizedName.values()]
    .sort((a, b) => String(a.name || '').localeCompare(String(b.name || ''), 'es'));
}

export function projectOperationalBranchOptions(cities = []) {
  const byBranch = new Map();

  for (const city of dedupeCitiesByNormalizedName(cities)) {
    const branchName = canonicalOperationalBranchName(city?.name);
    const branchKey = normalizeCityKey(branchName);
    if (!branchKey) continue;
    const current = byBranch.get(branchKey);
    if (!current) {
      byBranch.set(branchKey, {
        ...city,
        name: branchName,
        equivalentCityIds: cityEquivalentIds(city)
      });
      continue;
    }
    const preferred = preferOperationalBranchCity(current, city);
    byBranch.set(branchKey, {
      ...preferred,
      name: branchName,
      equivalentCityIds: [...new Set([...cityEquivalentIds(current), ...cityEquivalentIds(city)])]
    });
  }

  return [...byBranch.values()]
    .sort((a, b) => String(a.name || '').localeCompare(String(b.name || ''), 'es'));
}

export async function loadUnifiedCityOptions(prisma) {
  const cities = await prisma.city.findMany({
    where: { NOT: { id: { startsWith: 'city_' } } },
    orderBy: { name: 'asc' }
  });
  return projectOperationalBranchOptions(cities);
}

async function loadUserTerritorialAccess(prisma, source = {}) {
  const sourceScope = sourceValue(source, 'userAccessScope') ?? sourceValue(source, 'accessScope');
  const sourceCities = sourceValue(source, 'userAccessCity') ?? sourceValue(source, 'scopeCity');
  const sourceVacancyId = sourceValue(source, 'userAccessVacancyId') ?? sourceValue(source, 'scopeVacancyId');
  if (sourceScope !== null && sourceScope !== undefined) {
    return {
      accessScope: normalizeUserAccessScope(sourceScope),
      scopeCity: sourceCities,
      scopeVacancyId: sourceVacancyId
    };
  }

  const userId = normalizeString(sourceValue(source, 'userId') || sourceValue(source, 'id'));
  const username = normalizeString(sourceValue(source, 'username'));
  if (!userId && !username) return null;
  if (!prisma?.appUser?.findUnique) return null;

  const user = await prisma.appUser.findUnique({
    where: userId ? { id: userId } : { username },
    select: { accessScope: true, scopeCity: true, scopeVacancyId: true, isActive: true }
  });
  if (!user?.isActive) return null;
  return {
    accessScope: normalizeUserAccessScope(user.accessScope),
    scopeCity: user.scopeCity,
    scopeVacancyId: user.scopeVacancyId
  };
}

async function configuredCityNamesForAccess(prisma, territorialAccess, accessScope) {
  const configuredCityNames = accessScope === 'ALL'
    ? []
    : normalizeUserAccessCities(territorialAccess.scopeCity);
  if (configuredCityNames.length || accessScope !== 'VACANCY' || !territorialAccess.scopeVacancyId) {
    return configuredCityNames;
  }
  if (!prisma?.vacancy?.findUnique) return configuredCityNames;
  const vacancy = await prisma.vacancy.findUnique({
    where: { id: territorialAccess.scopeVacancyId },
    select: { city: true }
  });
  const vacancyCity = normalizeString(vacancy?.city);
  return vacancyCity ? [vacancyCity] : configuredCityNames;
}

function optionContainsRequestedId(city, requestedCityIds) {
  return cityEquivalentIds(city).some((id) => requestedCityIds.includes(id));
}

function flattenedCityIds(cities = []) {
  return [...new Set(cities.flatMap((city) => cityEquivalentIds(city)))];
}

/**
 * Única proyección territorial para módulos operativos.
 *
 * La autoridad persistida vive en AppUser.accessScope + AppUser.scopeCity, la misma
 * configuración usada por Reclutamiento. Este adaptador solo traduce nombres de
 * ciudad a los IDs canónicos del catálogo operativo y aplica un filtro temporal
 * opcional de la pantalla de Asignaciones; no persiste un segundo alcance.
 */
export async function resolveUserCityScope(prisma, source = {}, options = {}) {
  const allCities = await loadUnifiedCityOptions(prisma);
  const allCityIds = flattenedCityIds(allCities);
  const appRole = normalizeString(sourceValue(source, 'userRole') || sourceValue(source, 'role'))?.toLowerCase();
  const requestedCityIds = normalizeStringList(options.requestedCityIds);
  const selectionExplicit = options.selectionExplicit === true;

  if (appRole === 'dev') {
    const selectedCities = selectionExplicit
      ? allCities.filter((city) => optionContainsRequestedId(city, requestedCityIds))
      : allCities;
    return {
      restricted: false,
      selectionExplicit,
      accessScope: 'ALL',
      configuredCityNames: [],
      allowedCities: allCities,
      allowedCityIds: allCityIds,
      selectedCities,
      selectedCityIds: flattenedCityIds(selectedCities),
      selectedCityNames: selectedCities.map((city) => city.name),
      unauthorizedRequestedCityIds: requestedCityIds.filter((id) => !allCityIds.includes(id))
    };
  }

  const territorialAccess = await loadUserTerritorialAccess(prisma, source);
  if (!territorialAccess) {
    return {
      restricted: true,
      selectionExplicit,
      accessScope: null,
      configuredCityNames: [],
      allowedCities: [],
      allowedCityIds: [],
      selectedCities: [],
      selectedCityIds: [],
      selectedCityNames: [],
      unauthorizedRequestedCityIds: requestedCityIds
    };
  }

  const accessScope = normalizeUserAccessScope(territorialAccess.accessScope);
  const configuredCityNames = await configuredCityNamesForAccess(prisma, territorialAccess, accessScope);
  const restricted = accessScope !== 'ALL';
  const allowedCities = restricted
    ? allCities.filter((city) => configuredCityNames.some((name) => operationalCityNamesEquivalent(name, city.name)))
    : allCities;
  const allowedCityIds = flattenedCityIds(allowedCities);
  const allowedIdSet = new Set(allowedCityIds);
  const selectedCities = selectionExplicit
    ? allowedCities.filter((city) => optionContainsRequestedId(city, requestedCityIds))
    : allowedCities;

  return {
    restricted,
    selectionExplicit,
    accessScope,
    configuredCityNames,
    allowedCities,
    allowedCityIds,
    selectedCities,
    selectedCityIds: flattenedCityIds(selectedCities),
    selectedCityNames: selectedCities.map((city) => city.name),
    unauthorizedRequestedCityIds: requestedCityIds.filter((id) => !allowedIdSet.has(id))
  };
}

export async function resolveEquivalentCityIds(prisma, cityId) {
  if (!cityId) return [];

  const selectedCity = await prisma.city.findFirst({
    where: { id: cityId, NOT: { id: { startsWith: 'city_' } } },
    select: { id: true, name: true }
  });
  if (!selectedCity) return [cityId];

  const cities = await prisma.city.findMany({
    where: { NOT: { id: { startsWith: 'city_' } } },
    select: { id: true, name: true }
  });

  const equivalentIds = cities
    .filter((city) => operationalCityNamesEquivalent(city.name, selectedCity.name))
    .map((city) => city.id);

  return equivalentIds.length ? equivalentIds : [selectedCity.id];
}
